Repository etcd-io/gofail, pull requests merged in 2025-03, with the labels that each got.

#105 chore: clean up golangci-lint
  .golangci.yaml
Labels: approved, size/S

#107 Updates golang toolchain to version 1.23.7
  .go-version
  go.mod
  integration/sleep/go.mod
Labels: size/XS, approved

#108 chore: enable testifylint
  .golangci.yaml
  code/binding_test.go
  code/rewrite_test.go
  runtime/failpoint_test.go
  runtime/runtime_test.go
  runtime/terms_test.go
Labels: approved, size/M
