Repository etcd-io/gofail, pull requests merged in 2025-02, with the labels that each got.

#97 Updates golang toolchain to version 1.22.12
  go.mod
Labels: size/XS, approved, ok-to-test

#99 Replace old coreos code of conduct with etcd community coc
  code-of-conduct.md
Labels: approved, size/M

#103 20250216 bump go linter 1.24
  .github/workflows/golangci-lint.yml
Labels: size/XS, approved

#102 Bump go 1.23.6
  .go-version
  go.mod
  integration/sleep/go.mod
Labels: approved, size/S
